### PR TITLE
dtype fix for the to_geotiff method

### PR DESCRIPTION
**Pull request by chelm**
A simple fix for support native dtypes and not assuming a dtype has been passed into the `to_geotiff` method.

### CODE REVIEW

**Comment by chelm** [comment]
@nricklin this cleared testing in travis. The earlier test failure was travis network issue with installing libs.

**Comment by nricklin** [comment]
ok, maybe merge master into it to verify it's good with all recent changes

**Comment by chelm** [comment]
Ok i merged master but my master branch had commit from the other PR for image metadata so i merged that branch into here to get the tests passing. Ideally we merge PR #130 first and then get this one in right after that and we'll be all good

**Comment by nricklin** [comment]
ok #130 is merged

**Comment by chelm** [comment]
@nricklin all good here too

**Pull request merged**
