### PR TITLE
WIP: RDA templates

### PR DESCRIPTION
**Pull request by Brett55**
- Modified gbdxtools to use templates vs graph generation
- All tests passing although CI is reporting failures even in Dev branch. 
    - 11 skipped geoeye and quickbird tests, need to find new data that is NOT acquisition types that was previously used in the test cases.
- Templates can probably be simplified/merged, this is a WIP
- Template id discovery via metadata search is flaky and hard to maintain. It is required per RDA team currently, perhaps named templates down the road.

### CODE REVIEW

**Review by rjpolackwich — APPROVED** [review]
All looks v well done. Nice job with the deep refactors at the driver/base level as well as the image class level refactors. RDA/Op class refactor look solid as well, nice job preserving the interface there. Code all solid. Should be merged today and look to push a new release, I would think.

**Review by drwelby — COMMENTED** [review]
So a random thing I ran into is that the DigitalGlobeStrip template and operator have different names for the same parameter. So the question is since DigitalGlobeStrip is the granddaddy of templates, should we adopt those parameter names as conventions? Or is it better to have these template parameters match the parameters that are fed to the operators? I'm leaning towards the latter (the way it is now).

**Comment by drwelby** [comment]
Can you add a document that describes the workflow for making a template and using it, should we need to add a new image class? Also, if we have to revise or update a template, what are the steps there?

**Comment by Brett55** [comment]
@drwelby I essentially copied the DigitalGlobeStrip template and matched the parameters that are fed to the operators. The real reason I copied the template was in case RDA team changes the template it doesn't break us. Probably pros and cons to using that template as well.

I can make a document that describes how to make a template. I think Graph Studio is best for making templates. 

As for updating templates, it is a pain. Currently I have to post a template (PUT is not allowed), and then link that new template Id to its respective metadata so it can be discoverable via tags (search). It's all very error prone and I'd prefer to have real names like `DigitalGlobeStrip`, and PUT would be nice.

**Review by drwelby — APPROVED** [review]
This looks good for merging into dev, next let's brainstorm how we can make maintaining the templates less of a pain.

**Pull request merged**
