### PR TITLE
Add generation of slippy map thumbnails, fix feature popup tables

### PR DESCRIPTION
**Pull request by drwelby**
`map` and `tilemap` still need a refactor but this gets in the automatic generation of embedded thumbnails for the slippy maps, and fixes the feature popup tables so they display at a sensible size.

### CODE REVIEW

**Comment by chelm** [comment]
We should talk about these functions and what they could and should be. Thinking one function, but this looks good to me. Also we need to think about what parts of gbdxtools are notebooks specific like these and how to best handle/group them

**Comment by drwelby** [comment]
I think this stuff doesn't really belong in `gbdxtools`, and as we build more notebooks there will probably be a need for `gbdxwidgets`. Beyond maps I could see other interactive things like sliders for thresholding, radio-button band selection for false color images, etc.

**Comment by chelm** [comment]
I agree, should figure out the pattern for it outside of gbdxtools starting with the map/tilemap methods. Those methods are pretty straightforward to imagine out of gbdxtools. The image band selection is a cool idea, would gbdxtools then be a dep of `gbdxwidgets`?

**Comment by drwelby** [comment]
The concept of generic Jupyter widgets for raster analysis is interesting, but I would expect that there would be enough DG-specific tools to justify it being dependent on `gbdxtools`.

I could also see `gbdxwidgets` providing interactive widgets for the ML side.

**Comment by chelm** [comment]
@drwelby totally. we've long wanted this. I'd like to also see it done in a little more sophisticated way than how those 2 map functions are being done currently (basically just brute forcing JS as strings into the browser).

**Pull request merged**
