### PR TITLE
GBDXA-367 Added RDA template creation guide

### PR DESCRIPTION
**Pull request by Brett55**
- Added RDA template creation guide

### CODE REVIEW

**Review by drwelby — COMMENTED** [review]
Looks good, how does this mesh with the template update script?

**Comment by Brett55** [comment]
@drwelby Currently the script is setup to read from the templates.json (I consider those gbdx owned templates), so more of an internal tool. 

The template update script could be modified to let users operate on their own list of templates. They would have to add the id to their template JSON for the script to work.

**Comment by drwelby** [comment]
Ok, so internally if had to support some new thing we would follow those directions to build the template, then we would paste the new template JSON into templates.json?

**Comment by Brett55** [comment]
@drwelby Not exactly, the template metadata I created manually for each image type. 

We could store the metadata next to the template json. Then the users could copy and paste [{template}, {template_metadata}]. The code would need to update both then.

**Pull request merged**
