### PR TITLE
Fix plotting 3-band false color images

### PR DESCRIPTION
**Pull request by drwelby**
Fixes the index error when specifying an arbitrary 3 bands to use for a false-color plot. Also adds a check and warning when trying to plot an image when the number of specified bands is not one or three.

### CODE REVIEW

**Comment by chelm** [comment]
@drwelby think there's any way to test this? I think read would need to be mocked to return some mocked ndarray

**Comment by drwelby** [comment]
What if we use an S3Image for plot testing?

**Comment by chelm** [comment]
Well s3Image is still rda based, so will still hit auth'd graphs. We could just checkin a small tif and stub read to return it and then test the plot methods

**Comment by drwelby** [comment]
I'm messing with a simple `PlotMock` object that uses an ndarray and the plotmixin.

**Comment by drwelby** [comment]
https://github.com/DigitalGlobe/gbdxtools/blob/plot-tests/tests/unit/test_plot.py

Simple test to make sure plots do or don't fail

**Comment by chelm** [comment]
Thanks @drwelby !

**Pull request merged**
