### PR TITLE
NamedTemporaryFile on Windows can be opened just once.

### PR DESCRIPTION
**Pull request by kkoperskidg**
Close the file before opening it with rastereio,
delete it in finally clause.
Also do not print out content of binary file when exception is caught.

### CODE REVIEW

**Comment by kkoperskidg** [comment]
Fix for getting chips on Windows

**Comment by chelm** [comment]
Looks good! Thanks @kkoperskidg - @pramukta do you want to review this one as well?

**Comment by chelm** [comment]
@kkoperskidg did you mean to close this PR? Maybe an accident?

**Review by pramukta — APPROVED** [review]

**Comment by pramukta** [comment]
Awesome! Nice catch and fix @kkoperskidg

**Comment by pramukta** [comment]
@chelm I think I closed the PR after merging

**Pull request merged**
