### PR TITLE
add id to constructor

### PR DESCRIPTION
**Pull request by lababidi**

### CODE REVIEW

**Comment by lababidi** [comment]
This is less of a cosmetic change, but more to open the discussion of creating a workflow from an existing workflow_id. This also means pulling down the necessary information to populate items such as Tasks.

**Comment by chelm** [comment]
@lababidi So this PR just adds accessing the input id from kwargs and not actually fetching the workflow? Is that what you're proposing?

**Comment by chelm** [comment]
I think the appropriate way to do this would be to create a new method on `Workflow` in `simpleworkflows.py` called `from_id` or something that would fetch the workflow and return a populated workflow object. 

The workflow class in `workflow.py` already has the get method.

**Comment by lababidi** [comment]
I learned about the workflow API after posting this but your idea is what I
had in mind before learning about the interface. Is there anything the
workflow object provides that the interface doesn't?

**Comment by chelm** [comment]
going to close this

**Pull request closed without merging**
